# Generated by Django 3.2.3 on 2021-06-07 12:11

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_beds_hospitals_bedsavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='district',
            field=base.models.NameField(max_length=20),
        ),
    ]
